package com.group100.wms.util;

import com.group100.wms.model.AttendanceRecord;
import com.group100.wms.model.Payroll;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;
import com.itextpdf.layout.properties.VerticalAlignment;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

// OOP Concepts Used:
// Encapsulation - All PDF generation logic and styling are contained within this class
// Abstraction - Complex PDF creation is simplified through methods like export(), exportPayroll(), exportAttendance()
// Polymorphism - Methods behave differently based on input data (generic vs payroll vs attendance)
// Inheritance - Uses iText classes (Document, Table, etc.) which extend base library classes

public final class PdfExporter {

    // Private constructor to prevent instantiation (utility class)
    private PdfExporter() {}

    // Primary theme color used in PDF
    private static final DeviceRgb COLOR_PRIMARY = new DeviceRgb(44, 62, 80);

    // White color for text on headers
    private static final DeviceRgb COLOR_WHITE   = new DeviceRgb(255, 255, 255);

    // Alternate row color for table styling
    private static final DeviceRgb COLOR_ROW_ALT = new DeviceRgb(248, 249, 250);

    // Accent color used for highlights (e.g., totals)
    private static final DeviceRgb COLOR_ACCENT  = new DeviceRgb(39, 174, 96);

    // Muted color used for secondary text
    private static final DeviceRgb COLOR_MUTED   = new DeviceRgb(149, 165, 166);

    // Border color for table cells
    private static final DeviceRgb COLOR_BORDER  = new DeviceRgb(222, 226, 230);

    // Formatter for displaying date and time in reports
    private static final DateTimeFormatter DT_FMT =
            DateTimeFormatter.ofPattern("dd MMMM yyyy, hh:mm a");

    // Adds a styled header section to the PDF document
    private static void addHeader(Document doc, String reportTitle, int month, int year) {
        doc.add(new Paragraph("Group 100 \u2014 Centralized Apparel WMS")
                .setBold().setFontSize(14).setFontColor(COLOR_PRIMARY)
                .setTextAlignment(TextAlignment.CENTER).setMarginBottom(0));

        doc.add(new Paragraph("Apparel Warehouse Management System \u2014 Sri Lanka")
                .setFontSize(9).setFontColor(COLOR_MUTED)
                .setTextAlignment(TextAlignment.CENTER).setMarginBottom(4));

        SolidLine line = new SolidLine(1.5f);
        line.setColor(COLOR_PRIMARY);
        doc.add(new LineSeparator(line).setMarginBottom(12));

        doc.add(new Paragraph(reportTitle + " \u2014 " + getMonthName(month) + " " + year)
                .setBold().setFontSize(18).setFontColor(COLOR_PRIMARY)
                .setTextAlignment(TextAlignment.CENTER).setMarginBottom(4));

        doc.add(new Paragraph("Generated: " + LocalDateTime.now().format(DT_FMT))
                .setFontSize(9).setFontColor(COLOR_MUTED)
                .setTextAlignment(TextAlignment.CENTER).setMarginBottom(16));
    }

    // Creates a styled table header cell
    private static Cell headerCell(String text) {
        return new Cell()
                .add(new Paragraph(text).setBold().setFontSize(10).setFontColor(COLOR_WHITE))
                .setBackgroundColor(COLOR_PRIMARY)
                .setPadding(8)
                .setBorder(new SolidBorder(COLOR_BORDER, 0.5f))
                .setTextAlignment(TextAlignment.CENTER)
                .setVerticalAlignment(VerticalAlignment.MIDDLE);
    }

    // Creates a styled table data cell with optional alternate row coloring
    private static Cell dataCell(String text, boolean altRow) {
        Cell cell = new Cell()
                .add(new Paragraph(text).setFontSize(9.5f).setFontColor(COLOR_PRIMARY))
                .setPadding(6)
                .setBorder(new SolidBorder(COLOR_BORDER, 0.5f))
                .setTextAlignment(TextAlignment.CENTER)
                .setVerticalAlignment(VerticalAlignment.MIDDLE);
        if (altRow) cell.setBackgroundColor(COLOR_ROW_ALT);
        return cell;
    }

    // Adds footer with system info and page numbers
    private static void addFooter(Document doc, PdfDocument pdfDoc) {
        doc.add(new Paragraph("\n"));
        doc.add(new Paragraph("Generated by Group100 WMS v1.0.0 \u2014 Centralized Apparel Warehouse Management System")
                .setFontSize(8).setFontColor(COLOR_MUTED)
                .setTextAlignment(TextAlignment.CENTER));

        int totalPages = pdfDoc.getNumberOfPages();
        for (int i = 1; i <= totalPages; i++) {
            doc.showTextAligned(
                    new Paragraph("Page " + i + " of " + totalPages)
                            .setFontSize(8).setFontColor(COLOR_MUTED),
                    PageSize.A4.getWidth() / 2, 20,
                    i, TextAlignment.CENTER, VerticalAlignment.BOTTOM, 0);
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // GENERIC EXPORT — used by all new controllers
    // ═══════════════════════════════════════════════════════════════

    // Exports generic tabular data into a styled PDF file
    public static void export(String title, String[] headers, List<String[]> data,
                              javafx.stage.Window owner) {
        javafx.stage.FileChooser fc = new javafx.stage.FileChooser();
        fc.setTitle("Save PDF");
        fc.setInitialFileName(title.replaceAll("\\s+", "_") + ".pdf");
        fc.getExtensionFilters().add(
                new javafx.stage.FileChooser.ExtensionFilter("PDF Files", "*.pdf"));
        java.io.File file = fc.showSaveDialog(owner);
        if (file == null) return;

        try (PdfWriter writer = new PdfWriter(file.getAbsolutePath());
             PdfDocument pdf = new PdfDocument(writer);
             Document doc = new Document(pdf, PageSize.A4)) {

            doc.setMargins(40, 36, 50, 36);

            doc.add(new Paragraph("Group 100 \u2014 Centralized Apparel WMS")
                    .setBold().setFontSize(14).setFontColor(COLOR_PRIMARY)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(0));
            doc.add(new Paragraph("Apparel Warehouse Management System \u2014 Sri Lanka")
                    .setFontSize(9).setFontColor(COLOR_MUTED)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(4));
            SolidLine line = new SolidLine(1.5f);
            line.setColor(COLOR_PRIMARY);
            doc.add(new LineSeparator(line).setMarginBottom(12));
            doc.add(new Paragraph(title)
                    .setBold().setFontSize(18).setFontColor(COLOR_PRIMARY)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(4));
            doc.add(new Paragraph("Generated: " + LocalDateTime.now().format(DT_FMT))
                    .setFontSize(9).setFontColor(COLOR_MUTED)
                    .setTextAlignment(TextAlignment.CENTER).setMarginBottom(16));
            doc.add(new Paragraph("Total Records: " + data.size())
                    .setFontSize(10).setFontColor(COLOR_ACCENT).setBold()
                    .setTextAlignment(TextAlignment.RIGHT).setMarginBottom(10));

            float[] widths = new float[headers.length];
            java.util.Arrays.fill(widths, 1f);
            Table table = new Table(UnitValue.createPercentArray(widths)).useAllAvailableWidth();
            for (String h : headers) table.addHeaderCell(headerCell(h));

            int row = 0;
            for (String[] rowData : data) {
                boolean alt = row % 2 == 1;
                for (String cell : rowData) table.addCell(dataCell(cell != null ? cell : "", alt));
                row++;
            }
            doc.add(table);
            addFooter(doc, pdf);
        } catch (Exception e) {
            System.err.println("[PDF] Export failed: " + e.getMessage());
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // LEGACY EXPORTS — used by existing payroll/attendance screens
    // ═══════════════════════════════════════════════════════════════

    // Exports payroll data into a formatted PDF report
    public static void exportPayroll(List<Payroll> payrolls, int month, int year,
                                     String outputPath) {
        try (PdfWriter writer = new PdfWriter(outputPath);
             PdfDocument pdf = new PdfDocument(writer);
             Document doc = new Document(pdf, PageSize.A4)) {

            doc.setMargins(40, 36, 50, 36);
            addHeader(doc, "Payroll Report", month, year);

            doc.add(new Paragraph("Total Records: " + payrolls.size())
                    .setFontSize(10).setFontColor(COLOR_ACCENT).setBold()
                    .setTextAlignment(TextAlignment.RIGHT).setMarginBottom(10));

            Table table = new Table(UnitValue.createPercentArray(
                    new float[]{1, 1.5f, 2, 1.5f, 1.5f, 1.5f, 1.5f, 1.5f, 2}))
                    .useAllAvailableWidth();

            String[] headers = {"ID", "Emp ID", "Base Salary", "OT Pay",
                    "Deductions", "EPF Emp", "EPF Employer", "ETF", "Net Salary"};
            for (String h : headers) table.addHeaderCell(headerCell(h));

            int row = 0;
            for (Payroll p : payrolls) {
                boolean alt = row % 2 == 1;
                table.addCell(dataCell(String.valueOf(p.getId()), alt));
                table.addCell(dataCell(String.valueOf(p.getEmployeeId()), alt));
                table.addCell(dataCell(String.format("Rs. %,.2f", p.getBaseSalary()), alt));
                table.addCell(dataCell(String.format("Rs. %,.2f", p.getOvertimePay()), alt));
                table.addCell(dataCell(String.format("Rs. %,.2f", p.getEpfEmployee()), alt));
                table.addCell(dataCell(String.format("Rs. %,.2f", p.getEpfEmployee()), alt));
                table.addCell(dataCell(String.format("Rs. %,.2f", p.getEpfEmployer()), alt));
                table.addCell(dataCell(String.format("Rs. %,.2f", p.getEtf()), alt));
                table.addCell(dataCell(String.format("Rs. %,.2f", p.getNetSalary()), alt));
                row++;
            }
            doc.add(table);
            addFooter(doc, pdf);

        } catch (Exception e) {
            System.err.println("[PDF] Failed to export payroll: " + e.getMessage());
        }
    }

    // Exports attendance records into a formatted PDF report
    public static void exportAttendance(List<AttendanceRecord> records, int month, int year,
                                        String outputPath) {
        try (PdfWriter writer = new PdfWriter(outputPath);
             PdfDocument pdf = new PdfDocument(writer);
             Document doc = new Document(pdf, PageSize.A4)) {

            doc.setMargins(40, 36, 50, 36);
            addHeader(doc, "Attendance Report", month, year);

            doc.add(new Paragraph("Total Records: " + records.size())
                    .setFontSize(10).setFontColor(COLOR_ACCENT).setBold()
                    .setTextAlignment(TextAlignment.RIGHT).setMarginBottom(10));

            Table table = new Table(UnitValue.createPercentArray(
                    new float[]{1, 1.5f, 2, 1.5f, 1.5f, 1.5f, 1.5f}))
                    .useAllAvailableWidth();

            String[] headers = {"ID", "Emp ID", "Date", "Clock In", "Clock Out", "Status", "OT Hours"};
            for (String h : headers) table.addHeaderCell(headerCell(h));

            int row = 0;
            for (AttendanceRecord r : records) {
                boolean alt = row % 2 == 1;
                table.addCell(dataCell(String.valueOf(r.getId()), alt));
                table.addCell(dataCell(String.valueOf(r.getEmployeeId()), alt));
                table.addCell(dataCell(r.getDate() != null ? r.getDate().toString() : "", alt));
                table.addCell(dataCell(r.getClockIn() != null ? r.getClockIn().toString() : "", alt));
                table.addCell(dataCell(r.getClockOut() != null ? r.getClockOut().toString() : "", alt));
                table.addCell(dataCell(r.getStatus(), alt));
                table.addCell(dataCell(String.format("%.2f", r.getOvertimeHours()), alt));
                row++;
            }
            doc.add(table);
            addFooter(doc, pdf);

        } catch (Exception e) {
            System.err.println("[PDF] Failed to export attendance: " + e.getMessage());
        }
    }

    // Returns the month name based on integer value (1–12)
    private static String getMonthName(int month) {
        String[] months = {"", "January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"};
        return (month >= 1 && month <= 12) ? months[month] : String.valueOf(month);
    }
}
